var first;
const para = document.getElementById("para");

document.getElementsByClassName("inputvals")[0].addEventListener("change",(event)=>{
    first= event.target.value
});

document.getElementsByClassName("inputvals")[1].addEventListener("change",(event)=>{ 
    alert(first+" "+event.target.value)
});

para.style.backgroundColor="yellow";
para.style.fontStyle="italic"



function getRandomImage() {  
    //declare an array to store the images  
    var randomImage = ["https://images.pexels.com/photos/858115/pexels-photo-858115.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "http://www.petsworld.in/blog/wp-content/uploads/2014/09/running-cute-puppies.jpg", "https://images.pexels.com/photos/142497/pexels-photo-142497.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "https://images.unsplash.com/photo-1543877087-ebf71fde2be1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", 
    "https://wi.wallpapertip.com/wsimgs/156-1565522_puppies-desktop-wallpaper-desktop-background-puppies.jpg","https://images.unsplash.com/photo-1501265976582-c1e1b0bbaf63?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"];  
      

      
    //generate a number and provide to the image to generate randomly  
    var number = Math.floor(Math.random()*randomImage.length);  
      
    //return the images generated by a random number  
    return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'"style="width:150px" />';  
    }  
    
var rep=[];
var a,b;
const btn=document.getElementById("btn");
btn.addEventListener("click",(e)=>{
    a = prompt("Enter number of row");
    b=prompt("Enter number of columns");
    matrix(a,b);
})

function matrix(a,b){
for(var i=0;i<a;i++){
    rep[i]=[];
}

    for(var i=0;i<a;i++){
        for(var j=0;j<b;j++){
         rep[i][j] = prompt(`enter element for row ${i} and column ${j}`);        }
    }

    for(var i=0;i<a;i++){
        for(var j=0;j<b;j++){
         console.log(rep[i][j])
        }
    }
}



function ten(m,n){
    if(m===10 || n===10){
        return true;
    }
    if(m+n===10){
        return tr
    }

    return (m===10 || n==10 || m+n===10)?true:false;
}

var res = ten(1,1);
console.log(res)


function score(x,y,z){
    return 3*x + 1*y + 0*z;
}
console.log(score(1,2,3));
